---
title: "Testing IPUMS Data"
author: "Amanda Regan"
date: "October 1, 2014"
output: html_document
---
```{r}
library(tidyr)
library(dplyr)
library(stringr)
library(mullenMisc)

getwd()
census <- read.csv('usa_00012.csv')
refined_data <- census %>% filter(YEAR == 1910 | YEAR == 1920) %>% select(YEAR, WARD, SEX, NFAMS, AGE, BPLD, OCC, NATIVITY,NATIVITY_MOM, AGE)
race_ids <- refined_data  %>% group_by(BPLD) %>% summarize(count = n())

head(classwrkd)
codes <- read.csv("test.csv", header = TRUE) %>% as.data.frame(row.names=NULL)

refined_data <- left_join(refined_data, codes, by = c("BPLD" = "CODE"))
#fix genders
refined_data$SEX[refined_data$SEX == "1"] <- "male"
refined_data$SEX[refined_data$SEX == "2"] <- "female"
write.csv(data, file = "data.csv")

natcodes <- read.csv("nativitycodes.csv", header = TRUE) %>% as.data.frame(row.names=NULL)
data <- left_join(data, natcodes)
refined_data <- data %>% filter(WARD == 21) %>% group_by(BIRTHPLACE) %>% summarize(count = n())
library(classInt)
intervals <- classIntervals(refined_data$AGE, 10, "pretty")
head(cut(refined_data$AGE, breaks = intervals$brks))
refined_data <- refined_data %>%
  mutate(age_classified = cut(AGE, intervals$brks))
data_long <- data %>% gather(category,type, BIRTHPLACE, Nativity_Type, age_classified, NFAMS, SEX)

data_long <- data_long %>% subset(select=c(YEAR, WARD, category, type))

write.csv(data_long , file="../data_longtest.csv", row.names=FALSE)
write.csv(data_long, file = "../data.csv")
```

Create a csv for ages with jenks and counts per ward per year. 
```{r}
refined_data <- as.data.frame(refined_data)
agegrps <- (subset(refined_data, select=c(YEAR, WARD, age_classified)))
agecount <- tally(group_by(agegrps, YEAR, WARD, age_classified), sort = TRUE)
agecount <- agecount %>% arrange(YEAR, WARD)
write.csv(agecount, file="../ages.csv", row.names = FALSE)
```

```{r}
years <-data %>% filter(YEAR == 1910) %>% filter(WARD == 1) %>% group_by(SEX) %>% summarize(count=n())
gender <- tally(group_by(data, YEAR, WARD, SEX), sort = TRUE) 
gender <-  rename(gender, c(SEX = "genderdimension", n = "gendercount"))
nativity <- tally(group_by(data, YEAR, WARD, Nativity_Type), sort = TRUE)
nativity <- nativity %>% rename(c(n = "nativity_count"))


agegrp <- tally(group_by(data, YEAR, WARD, age_classified), sort = TRUE) 
birthpl <- tally(group_by(data, YEAR, WARD, BIRTHPLACE), sort = TRUE) 

occupation <- tally(group_by(data, YEAR, WARD, OCC), sort = TRUE) %>% rename(c(OCC = "dimension", n = "count"))
totalS <- rbind(gender, nativity, agegrp, birthpl, occupation)
write.csv(totalS, file="data_long.csv", row.names = FALSE)
write.csv(wide,file="../data_gender.csv", row.names = FALSE)
all <- 
fix <- read.csv("../data_gender.csv", header= TRUE) 
fix <- as.data.frame(fix)
fix <- spread(gender, count, -year, -ward)
gender <- gender %>% spread(gender, count, -YEAR, -WARD)

wide <- reshape(fix, timevar="sex", idvar = c("year","ward"), direction = "wide")



%>% tally(SEX, sort = TRUE)
tally(tally(plays_by_year))


```





```{r}
census <- read.csv('usa_00010.csv')
PosseDist <- census %>% filter(YEAR == 1910) %>% group_by(ENUMDIST) %>% summarize(Count = n())
head(PosseDist)
```


dataframe of all gyms gecoded
```{r}
library(ggmap)
addresses <- data.frame(name = c("316 Huntington Ave, Boston MA",
                              "48 Boylston, Boston MA",
                              "309 Washington, Boston MA",
                              "175 Mass Ave, Boston MA",
                              "75 Tyler, Boston MA",
                              "40 Berkeley, Boston MA",
                              "73 Causeway, Boston MA",
                              "42 St. Botolph, Boston MA",
                              "779 Beacon St, Boston MA",
                              "198 Clarendon, Boston MA"),
           stringsAsFactors = FALSE)
cities_geocoded <- geocode(addresses$name)
addresses <- cbind(addresses, cities_geocoded)
```

Now a map
```{r}
library(ggplot2)
ggplot(addresses, aes(x = lon, y = lat)) +
  geom_point() +
  geom_text(aes(label = name), vjust = -1) +
  coord_map()
```

Useful but 